### ISSUE TITLE
Paralell Request Getting Slower and Slower

### ISSUE THREAD

**Issue by revocengiz** [AdaskoTheBeAsT/WkHtmlToX#3]
Hi,
I did some load testing as I promised. When making single request, response time is roughly 500ms.
But making 20 parallel request response time getting slower and slower.
I prepared a test project with your package and current pdf conversion I use by starting new process in every request.
Because spawning multiple processes cause cpu peak I made request throttling(max 5 process) bu using https://www.tpeczek.com/2017/08/implementing-concurrent-requests-limit.html

Here ise demo project (I used Apache Benchmark for load testing)
https://github.com/revocengiz/PdfConvert

Maybe adding some king of multiple cached process thread improve performance.

Thank you.
Result preview
![loadtest](https://user-images.githubusercontent.com/6932535/109635467-7760b900-7b5b-11eb-8cf9-1a55e0c59e67.gif)

**Comment by AdaskoTheBeAsT** [comment]
Hi,

it is by design - converting is done is separate one thread which operates on BlockingQueue - documents are converted sequentially - lib is not designed to operate on hundreds thousands of html document to convert - there is also some active issue on multithreading https://github.com/wkhtmltopdf/wkhtmltopdf/issues/4130
